# This is a basic workflow 

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: snyk/actions@0.3.0

      # Runs a single command using the runners shell
      - name: Snyk Monitor
        with: 
         command: test
         args: --all-projects
         continue-on-error: true
         json: snyk.json
         env: 
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
